In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = [59.42649421, 55.58726505, 65.23300987, 66.13738074, 60.91996085,
       55.85811706, 58.0582923 , 60.61091199, 64.89652398, 69.32840032,
       60.35299079, 61.97565806, 68.18860035, 64.31453248, 56.65074281,
       56.57132735, 61.56030852, 64.1639614 , 64.60110847, 64.64751662,
       58.31443559, 54.25999223, 58.84301377, 63.46653987, 60.07288485,
       51.86696962, 53.86787105, 56.98659755, 55.84219098, 56.44303203]

y = [59.99811522, 55.11109184, 64.35660765, 63.47401643, 56.71585792,
       54.32954589, 59.71421953, 61.40437889, 65.96258278, 72.66086436,
       60.73616546, 60.32574465, 67.26776508, 62.42656374, 55.38496873,
       57.38024325, 60.39843669, 61.81243858, 64.33648484, 64.86741143,
       58.75313726, 55.77588005, 59.46862275, 61.48970191, 57.85264649,
       53.21652635, 55.80486898, 57.99794322, 55.9033371 , 53.90241318]

In [4]:
# calculate the means of x and y
np.mean(x)
np.mean(y)

59.96095267500001

In [5]:
# convert x and y into a 2-dimensional array where x and y are each a row
z_row = np.array([x, y])
z_row

array([[59.42649421, 55.58726505, 65.23300987, 66.13738074, 60.91996085,
        55.85811706, 58.0582923 , 60.61091199, 64.89652398, 69.32840032,
        60.35299079, 61.97565806, 68.18860035, 64.31453248, 56.65074281,
        56.57132735, 61.56030852, 64.1639614 , 64.60110847, 64.64751662,
        58.31443559, 54.25999223, 58.84301377, 63.46653987, 60.07288485,
        51.86696962, 53.86787105, 56.98659755, 55.84219098, 56.44303203],
       [59.99811522, 55.11109184, 64.35660765, 63.47401643, 56.71585792,
        54.32954589, 59.71421953, 61.40437889, 65.96258278, 72.66086436,
        60.73616546, 60.32574465, 67.26776508, 62.42656374, 55.38496873,
        57.38024325, 60.39843669, 61.81243858, 64.33648484, 64.86741143,
        58.75313726, 55.77588005, 59.46862275, 61.48970191, 57.85264649,
        53.21652635, 55.80486898, 57.99794322, 55.9033371 , 53.90241318]])

In [6]:
# convert x and y into a 2-dimensional array where x and y are each a column
z = np.zeros((len(x), 2))
z[:,0] = x
z[:,1] = y
z

array([[59.42649421, 59.99811522],
       [55.58726505, 55.11109184],
       [65.23300987, 64.35660765],
       [66.13738074, 63.47401643],
       [60.91996085, 56.71585792],
       [55.85811706, 54.32954589],
       [58.0582923 , 59.71421953],
       [60.61091199, 61.40437889],
       [64.89652398, 65.96258278],
       [69.32840032, 72.66086436],
       [60.35299079, 60.73616546],
       [61.97565806, 60.32574465],
       [68.18860035, 67.26776508],
       [64.31453248, 62.42656374],
       [56.65074281, 55.38496873],
       [56.57132735, 57.38024325],
       [61.56030852, 60.39843669],
       [64.1639614 , 61.81243858],
       [64.60110847, 64.33648484],
       [64.64751662, 64.86741143],
       [58.31443559, 58.75313726],
       [54.25999223, 55.77588005],
       [58.84301377, 59.46862275],
       [63.46653987, 61.48970191],
       [60.07288485, 57.85264649],
       [51.86696962, 53.21652635],
       [53.86787105, 55.80486898],
       [56.98659755, 57.99794322],
       [55.84219098,

In [7]:
# calculate the means of x and y using one call to np.mean 
# (use the 2-dimensional array you made)

np.mean(z, axis=0)



array([60.30155436, 59.96095268])

In [8]:
# calculate the element-wise mean of x and y
np.mean(z, axis=1)

array([59.71230472, 55.34917844, 64.79480876, 64.80569859, 58.81790939,
       55.09383148, 58.88625591, 61.00764544, 65.42955338, 70.99463234,
       60.54457813, 61.15070135, 67.72818272, 63.37054811, 56.01785577,
       56.9757853 , 60.9793726 , 62.98819999, 64.46879666, 64.75746403,
       58.53378643, 55.01793614, 59.15581826, 62.47812089, 58.96276567,
       52.54174799, 54.83637001, 57.49227038, 55.87276404, 55.17272261])

In [9]:
# calculate the element-wise maximum of x and y
np.maximum(x,y)

array([59.99811522, 55.58726505, 65.23300987, 66.13738074, 60.91996085,
       55.85811706, 59.71421953, 61.40437889, 65.96258278, 72.66086436,
       60.73616546, 61.97565806, 68.18860035, 64.31453248, 56.65074281,
       57.38024325, 61.56030852, 64.1639614 , 64.60110847, 64.86741143,
       58.75313726, 55.77588005, 59.46862275, 63.46653987, 60.07288485,
       53.21652635, 55.80486898, 57.99794322, 55.9033371 , 56.44303203])

In [11]:
# calculate the serial correlation between x_t and x_{t-1}
np.corrcoef(x[1:], x[:-1])

array([[1.        , 0.45059817],
       [0.45059817, 1.        ]])

In [10]:
# calculate the mean of x when x is greater than 60
x_arr = np.array(x)
np.mean(x_arr[x_arr > 60])

63.7793930725

In [11]:
# sort the values
np.sort(x_arr)

array([51.86696962, 53.86787105, 54.25999223, 55.58726505, 55.84219098,
       55.85811706, 56.44303203, 56.57132735, 56.65074281, 56.98659755,
       58.0582923 , 58.31443559, 58.84301377, 59.42649421, 60.07288485,
       60.35299079, 60.61091199, 60.91996085, 61.56030852, 61.97565806,
       63.46653987, 64.1639614 , 64.31453248, 64.60110847, 64.64751662,
       64.89652398, 65.23300987, 66.13738074, 68.18860035, 69.32840032])